### ISSUE TITLE
RejectedExecutionException in m2e 

### ISSUE THREAD

**Issue by snjeza** [takari/aether-connector-okhttp#27]
The issue has been introduced with https://github.com/takari/aether-connector-okhttp/commit/32ce3f86e2b6bc292b9f07d8306bc01a0c973605
It can be reproduced by importing spring-petclinic into an empty maven workspace.
See https://github.com/eclipse/eclipse.jdt.ls/pull/1369 and https://ci.eclipse.org/ls/job/jdt-ls-pr/1903/

**Comment by Eskibear** [comment]
By a glance, I think it's caused by https://github.com/takari/aether-connector-okhttp/commit/32ce3f86e2b6bc292b9f07d8306bc01a0c973605#diff-5ff8f4f0644941e5adcc1e24d6fd4df1R804-R806 which should not be added. 
When you cancel a case, the thread pool is shutdown, thus no task can be submitted any more. 

Let me verify that.
